### ISSUE TITLE
App crashing on Profile fragment on specific devices

### ISSUE THREAD

**Issue by FullBinaryAlchemist** [FullBinaryAlchemist/SecurityApplication#63]
App crashes on trying to load profile fragement on Redmi Note 4 running MIUI 11 and Android 7.0 . Works fine on Android 9.

Steps to reproduce:
1.Sign in using dgdivyanshu or dgdivyanshu+1 credential
2.Touch Profile tab.

Suspected cause:
NullPointerException in DisplayData() on getGender() line#258

```
12/20 12:23:26: Launching 'app' on Xiaomi Redmi Note 4.
$ adb shell am start -n "com.example.securityapplication/com.example.securityapplication.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 13419 on device 'xiaomi-redmi_note_4-5e48cc440104'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application com.example.securityapplication can be debugged on port 8100...
W/System: ClassLoader referenced unknown path: /data/app/com.example.securityapplication-1/lib/arm64
W/ResourceType: No package identifier when getting name for resource number 0x00000000
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
D/FirebaseApp: com.google.firebase.iid.FirebaseInstanceId is not linked. Skipping initialization.
D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
D/FirebaseApp: com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
I/FirebaseInitProvider: FirebaseApp initialization successful
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
    [FirebaseAuth:] Preparing to create service connection to gms implementation
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/AccessibilityManager: current package=com.example.securityapplication, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
        at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
        at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
        at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
        at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
        at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.example.securityapplication.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:191)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6845)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2700)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2808)
        at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1541)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:165)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6375)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:912)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:802)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.securityapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.securityapplication-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:74)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
        at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
        at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
        at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
        at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.example.securityapplication.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:191)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6845)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2700)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2808)
        at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1541)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:165)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6375)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:912)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:802)
I/TypefaceUtils: Typeface has no familyName field
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
W/ResourceType: No package identifier when getting name for resource number 0x00000000
I/DynamiteModule: Considering local module com.google.android.gms.signinbutton_dynamite:0 and remote module com.google.android.gms.signinbutton_dynamite:2
    Selected remote version of com.google.android.gms.signinbutton_dynamite, version >= 2
W/System: ClassLoader referenced unknown path: 
I/DynamiteLoaderV2: [71] Dynamitemodulesa
W/System: ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000137/n/arm64-v8a
W/ResourceType: No package identifier when getting name for resource number 0x00000000
D/FirebaseHelper: Created new FirebaseHelperInstance
D/FirebaseHelper: Initializing Databse References... 
D/FirebaseHelper: Firebase Initialization complete
D/MainActivity: Checkig user status...
D/FirebaseHelper: Initializing Google SignIN Client
D/GoogleSignIn: Created new googleFirebaseInstance
D/FirebaseHelper: FirebaseHelperInstance Exists
    Initializing Databse References... 
D/FirebaseHelper: Firebase Initialization complete
I/Timeline: Timeline: Activity_launch_request time:735559124 intent:Intent { cmp=com.example.securityapplication/.navigation }
D/MainActivity: UI updated successfully
D/SOS Timer: Timer started
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/SOS Player: Inside onStartCOmmand : Stop =0
    detectSOSPattern initialised
W/MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
E/HAL: PATH3 /odm/lib64/hw/gralloc.qcom.so
E/HAL: PATH2 /vendor/lib64/hw/gralloc.qcom.so
    PATH1 /system/lib64/hw/gralloc.qcom.so
    PATH3 /odm/lib64/hw/gralloc.msm8953.so
    PATH2 /vendor/lib64/hw/gralloc.msm8953.so
    PATH1 /system/lib64/hw/gralloc.msm8953.so
I/Toast: Show toast from OpPackageName:com.example.securityapplication, PackageName:com.example.securityapplication
D/SOS Timer: Time remaining:9
D/DH.java: User object sent
D/NavigatonFragment: User:null
D/NavigatonFragment: Attempt to invoke virtual method 'void com.example.securityapplication.model.User.setImei(java.lang.String)' on a null object reference
D/FirebaseHelper: FirebaseHelperInstance Exists
D/FirebaseHelper: Initializing Databse References... 
D/FirebaseHelper: Firebase Initialization complete
    Initializing Google SignIN Client
D/checking: oncreate option menu 3 is running
D/Database: Sos Contact Details loaded in Cursor
D/checking4: false
    false
D/checking4: false
D/checking: oncreate option menu is runningfalse
I/Adreno: QUALCOMM build                   : 01d2d27, I3d52eaf367
    Build Date                       : 12/10/16
    OpenGL ES Shader Compiler Version: XE031.09.00.03
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
I/Mainactivity destroyed: onDestroy!
D/SOS Timer: Time remaining:8
D/Paid12345: schin1   true
D/FirebaseUsername:     2 dgdivyanshu@gmail.com
D/DH.java: User object set
D/SOS_Database: SOS contacts added successfully
D/NavigatonFragment: dgdivyanshu@gmail.com
    dgdivyanshu@gmail.com
    Inside recheckUserAuthentication
    Imei of device:866257031203002
    Imei from firebase:866257031203002
D/SendSMSService: initContacts:
D/SendSMSServcie: SosContacts size:1
D/SendSMSService: contact.get(0):9819931901
    contactList[0]:9819931901
D/SOS Timer: Time remaining:7
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@1ef202f
I/art: Do partial code cache collection, code=25KB, data=30KB
    After code cache collection, code=25KB, data=29KB
I/art: Increasing code cache capacity to 128KB
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9a0620f
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@dc4829c
D/SOS Timer: Time remaining:6
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@d616f51
    BoostFramework() : mPerf = com.qualcomm.qti.Performance@c0d43b6
D/Database: No records Found
D/Profile: No Data found
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.securityapplication, PID: 13419
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
        at com.example.securityapplication.profile_fragment.DisplayData(profile_fragment.java:258)
        at com.example.securityapplication.profile_fragment.onViewCreated(profile_fragment.java:108)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
I/Process: Sending signal. PID: 13419 SIG: 9
Process 13419 terminated.

```

**Comment by FullBinaryAlchemist** [comment]
@sachinsav Have a look

**Comment by FullBinaryAlchemist** [comment]
Seems to be working now
